### PR TITLE
Add xfrm support: netlink-packet-xfrm crate review

### PR DESCRIPTION
**Pull request by zooknotic**
I'm not sure if I'm using this new-crate-review repo as intended, but this request is to add a new crate repo to the project named netlink-packet-xfrm. This patch is based on my original pull request from the old repo here: https://github.com/little-dude/netlink/pull/298

This crate is intended to support parse/emit of the netlink xfrm structs and messages for IPsec.
If this crate is accepted, I will follow up with a second new crate request for xfrmnetlink, which depends on this.

### CODE REVIEW

**Comment by cathay4t** [comment]
Sorry for the late response.

I have created the git repo at https://github.com/rust-netlink/netlink-packet-xfrm and invited you as admin of that repo.

And also released 0.1 at https://crates.io/crates/netlink-packet-xfrm , please provide your crates.io  account, so I could grant you the permission to update crates.io also.

**Comment by cathay4t** [comment]
Besides providing account name of crates.io

Please consider add documentation and tests to this new git repo. Thank you!

**Comment by zooknotic** [comment]
Thanks. I've added crates.io for my account. This repo has some tests in tests.rs, but admittedly not much documentation. See my second PR for the xfrmnetlink new crate review. That repo will have higher level examples on how the netlink-packet-xfrm structs are used.

**Comment by cathay4t** [comment]
* I have invite you in crates.io.
* CI enabled in `netlink-packet-xfrm`.
* Removed reexports and release 0.2.0 with CHANGELOG file

Initially, you may use your admin right to force merging PRs. I will review project every bundle release(6 months).

Closing as my work is done for new crate request.

**Pull request closed without merging**
