### PR TITLE
Add xfrm support: xfrmnetlink crate review 

### PR DESCRIPTION
**Pull request by zooknotic**
This request is to add a new crate repo to the project named xfrmnetlink. This crate builds on the newly created netlink-packet-xfrm repo and implements a more usable interface for the netlink send/receive messaging to manipulate IPsec policy and state in the kernel. The examples directory contains several programs that show how commands similar to the iproute2 xfrm tools can be implemented.

### CODE REVIEW

**Comment by cathay4t** [comment]
Please update your crate to this bundle release:
https://github.com/rust-netlink/.github/discussions/4

Generally:
 * Use `netlink-packet-xfrm` 0.2.0
 * Use `non_exhaustive`.
 * No reexport.

**Comment by zooknotic** [comment]
I believe all the requested changes have been made.

**Comment by cathay4t** [comment]
Sorry for the wait. I will attend this on Friday(2023-Feb-17)

**Comment by cathay4t** [comment]
@zooknotic I have created https://github.com/rust-netlink/xfrmnetlink with you assigned as admin.

**Comment by cathay4t** [comment]
I am fixing the clippy errors and enabling CI in case of overlap.

**Comment by cathay4t** [comment]
@zooknotic I tried to fix up the clippy errors, but failed. In stead me spending time polishing on code I don't actually understand, please try to fix https://github.com/rust-netlink/xfrmnetlink/issues/2 before next release.

If you have problem on redefining the API, please let me know.
Unless cargo clippy is passing, please do not release it to crates.io. Thank you!

**Comment by cathay4t** [comment]
Closing as the https://github.com/rust-netlink/xfrmnetlink is created.

**Pull request closed without merging**
